### ISSUE TITLE
登陆验证

### ISSUE THREAD

**Issue by greatzh** [yllhwa/FileWorker#7]
您好，非常感谢您的工作，有一个问题是这里的登录验证是没有没有实现啊，似乎是输入任何密码都可以进入，而不用匹配环境变量中设置的密码。
https://github.com/yllhwa/FileWorker/blob/9aa9528bd0749a0aa4006ff4811eaa19172800d9/src/pages/LoginPage.vue#L11C1-L22C10

**Comment by yllhwa** [comment]
密码错误调用后端接口会出错跳回登录

**Comment by greatzh** [comment]
噢噢，谢谢您的回复，以为是密码错误就进入不了首页，现在我明白了！！

**Comment by 3377** [comment]
改成密码错误进不去，很难吗。。。这个坑坑了我1个小时。。
